theme: jekyll-theme-slate
title: OPE - Self Hosted Canvas LMS Server
description: OPE (Open Prison Education) - The easiest and most secure way to setup a self hosted, prison ready Canvas LMS for both offline and cloud use.
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
github:
  tar_url: 
  zip_url: https://github.com/operepo/ope_server_sync_binaries/archive/refs/heads/master.zip
  #another_url: another value
